import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { KeyRound, Users, ClipboardList } from 'lucide-react';

export default function AdminConsole({ accessToken }) {
  const [users, setUsers] = useState([]);
  const [audit, setAudit] = useState([]);
  const [form, setForm] = useState({ username: '', password: '', role: 'analyst' });
  const [error, setError] = useState(null);
  const load = useCallback(() => { const headers = { Authorization: `Bearer ${accessToken}` }; return Promise.all([axios.get('http://127.0.0.1:8000/api/v1/admin/users', { headers }), axios.get('http://127.0.0.1:8000/api/v1/admin/audit', { headers })]).then(([userResponse, auditResponse]) => { setUsers(userResponse.data.users); setAudit(auditResponse.data.audit); }).catch((requestError) => setError(requestError.response?.data?.detail || 'Administrator access required.')); }, [accessToken]);
  useEffect(() => { load(); }, [load]);
  const createUser = async (event) => { event.preventDefault(); try { await axios.post('http://127.0.0.1:8000/api/v1/admin/users', form, { headers: { Authorization: `Bearer ${accessToken}` } }); setForm({ username: '', password: '', role: 'analyst' }); load(); } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to create user.'); } };

  return <section className="space-y-6"><div><p className="eyebrow">Access governance</p><h2 className="text-xl font-bold text-white mt-1">Administrator Console</h2></div>{error && <div className="p-3 rounded-lg border border-red-500/30 bg-red-500/10 text-xs text-red-300">{error}</div>}<div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="bg-cardBg border border-slate-700/60 rounded-xl p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-slate-200"><Users size={17} className="text-cyan-400" /> User Directory</h3><div className="mt-4 space-y-2">{users.map((user) => <div key={user.username} className="flex justify-between p-3 rounded-lg bg-slate-900/40 text-xs"><span className="text-slate-200">{user.username}</span><span className="text-cyan-400 uppercase">{user.role}</span></div>)}</div><form onSubmit={createUser} className="mt-5 space-y-2"><input required placeholder="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} className="w-full bg-slate-950/60 border border-slate-700 rounded-md p-2 text-xs text-white" /><input required type="password" placeholder="Temporary password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="w-full bg-slate-950/60 border border-slate-700 rounded-md p-2 text-xs text-white" /><div className="flex gap-2"><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="flex-1 bg-slate-950/60 border border-slate-700 rounded-md p-2 text-xs text-white"><option>analyst</option><option>lead</option><option>admin</option></select><button className="px-3 rounded-md bg-cyan-600 text-xs font-semibold text-white"><KeyRound size={14} className="inline mr-1" />Create</button></div></form></div><div className="bg-cardBg border border-slate-700/60 rounded-xl p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-slate-200"><ClipboardList size={17} className="text-cyan-400" /> Audit Trail</h3><div className="mt-4 space-y-2 max-h-96 overflow-y-auto">{audit.map((entry, index) => <div key={`${entry.created_at}-${index}`} className="p-3 rounded-lg bg-slate-900/40"><p className="text-xs text-slate-200">{entry.action} <span className="text-cyan-300">{entry.resource}</span></p><p className="mt-1 text-[10px] text-slate-500">{entry.username} · {entry.created_at}</p></div>)}</div></div></div></section>;
}
