from datetime import datetime, timezone
from typing import Any


def build_cybercrime_complaint(incident: dict[str, Any]) -> dict[str, Any]:
    assessment = incident.get("assessment") or {}
    indicators = assessment.get("indicators", incident.get("indicators", []))
    iocs = assessment.get("iocs", incident.get("iocs", []))
    incident_id = incident.get("id") or f"INC-{incident.get('database_id', 'unknown')}"
    evidence_lines = [f"- {item.get('name', 'Indicator')}: {item.get('score', 'observed')}" for item in indicators[:10]]
    ioc_lines = [f"- {item.get('type', 'indicator')}: {item.get('value', item.get('indicator', 'unknown'))}" for item in iocs[:10]]
    body = "\n".join([
        "Subject: Cybercrime incident report - CyberGuard " + str(incident_id),
        "",
        "I am reporting a suspected cybercrime incident detected by CyberGuard.",
        f"Incident reference: {incident_id}",
        f"Detected category: {incident.get('category', 'unknown')}",
        f"Risk level: {incident.get('risk_level', incident.get('riskLevel', 'unknown'))}",
        f"Risk score: {incident.get('risk_score', incident.get('riskScore', 0))}%",
        f"Observed at: {incident.get('created_at', datetime.now(timezone.utc).isoformat())}",
        "",
        "Original evidence:",
        str(incident.get('payload', 'Not available'))[:5000],
        "",
        "Detection indicators:",
        "\n".join(evidence_lines) or "- No structured indicators recorded",
        "",
        "Indicators of compromise:",
        "\n".join(ioc_lines) or "- None extracted",
        "",
        "Requested action: Please review this incident and advise on protective or investigative steps.",
        "Generated by CyberGuard. Verify all details before submitting to cybercrime.gov.in or law enforcement.",
    ])
    return {"incident_id": incident_id, "portal": "https://cybercrime.gov.in", "helpline": "1930", "subject": f"Cybercrime incident report - {incident_id}", "body": body, "format": "plain-text draft"}
